ALTER TABLE viewer_suspicion_scores
    ADD COLUMN IF NOT EXISTS short_career_avg_fan_gain DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS short_career_p50_fan_gain DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS short_career_p90_fan_gain DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS short_career_p95_fan_gain DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS short_career_max_fan_gain DOUBLE PRECISION NOT NULL DEFAULT 0;