// Included by the owning module to preserve private field visibility.

const TOKENS: &[&str] = &[
    "daily-missions",
    "regular-login-cycle",
    "daily-jewel-pack",
    "speculative_income",
    "temporary_story_rewards",
    "racing_carnival_mission",
    "masters_challenge_rewards",
    "story_event_rewards",
    "factor_research_rewards",
    "scenario_evaluation_rewards",
    "main_story_rewards",
    "limited_login_rewards",
    "limited_mission_rewards",
    "racing_carnival_rewards",
    "trainer_skills_test_rewards",
    "champions_meeting_result",
    "club_rank",
    "league_of_heroes_rank",
    "legend_race_clears",
    "strongest_team_reward_tier",
    "team_trials_class",
    "monthly_shop_tickets",
    "champions_meeting_round_income",
    "random_gameplay_income",
    "training_pass",
    "none",
    "include",
    "median",
    "open_first",
    "open_second",
    "open_third",
    "champion",
    "silver_4",
    "platinum_4",
    "opponents_1",
    "opponents_2",
    "all",
    "clears_only",
    "score_only",
    "clear_1",
    "clear_2",
    "clear_3",
    "tier_1",
    "points_220000",
    "class_2",
    "class_3",
    "class_4",
    "class_5",
    "class_6",
    "friend_points",
    "low_investment",
    "competitive",
    "meta_highroller",
    "low",
    "medium",
    "high",
    "free",
    "paid",
    "premium",
    "__default_schedule__",
    "__excluded__",
    "rank_1",
    "rank_2",
    "rank_3",
    "rank_4",
    "rank_5",
    "rank_6",
    "rank_7",
    "rank_8",
    "rank_9",
    "rank_10",
    "rank_11",
    "login_milestone_rewards",
    "seasonal_gift_rewards",
    "valentines_gift_rewards",
    "white_day_gift_rewards",
    "christmas_gift_rewards",
];

const CURRENCIES: &[&str] = &[
    "free_jewels",
    "paid_jewels",
    "uma_ticket",
    "support_ticket",
    "rainbow_crystal",
    "gold_crystal",
    "rainbow_full_crystal",
    "gold_full_crystal",
];

const CADENCES: &[&str] = &["once", "daily", "weekly", "monthly", "interval"];

const BANNER_KINDS: &[&str] = &["character", "support", "paid", "other"];

const PRESET_IDS: &[&str] = &["conservative", "casual", "active", "completionist"];

#[derive(Debug, FromRow)]
struct LegacyStateRow {
    user_id: Uuid,
    revision: i64,
    collection: Value,
}
